export const countriesData = [
  {
    name: "United States",
    states: [
      {
        name: "California",
        cities: [
          "Los Angeles",
          "San Francisco",
          "San Diego",
          "Sacramento",
          "San Jose",
          "Fresno",
          "Long Beach",
          "Oakland",
          "Bakersfield",
          "Anaheim",
        ],
      },
      {
        name: "New York",
        cities: [
          "New York City",
          "Buffalo",
          "Rochester",
          "Yonkers",
          "Syracuse",
          "Albany",
          "New Rochelle",
          "Mount Vernon",
          "Schenectady",
          "Utica",
        ],
      },
      {
        name: "Texas",
        cities: [
          "Houston",
          "San Antonio",
          "Dallas",
          "Austin",
          "Fort Worth",
          "El Paso",
          "Arlington",
          "Corpus Christi",
          "Plano",
          "Laredo",
        ],
      },
      {
        name: "Florida",
        cities: [
          "Jacksonville",
          "Miami",
          "Tampa",
          "Orlando",
          "St. Petersburg",
          "Hialeah",
          "Tallahassee",
          "Fort Lauderdale",
          "Port St. Lucie",
          "Cape Coral",
        ],
      },
      {
        name: "Illinois",
        cities: [
          "Chicago",
          "Aurora",
          "Rockford",
          "Joliet",
          "Naperville",
          "Springfield",
          "Peoria",
          "Elgin",
          "Waukegan",
          "Cicero",
        ],
      },
    ],
  },
  {
    name: "Canada",
    states: [
      {
        name: "Ontario",
        cities: [
          "Toronto",
          "Ottawa",
          "Hamilton",
          "London",
          "Kitchener",
          "Windsor",
          "Oshawa",
          "Barrie",
          "Guelph",
          "Kingston",
        ],
      },
      {
        name: "Quebec",
        cities: [
          "Montreal",
          "Quebec City",
          "Laval",
          "Gatineau",
          "Longueuil",
          "Sherbrooke",
          "Saguenay",
          "Lévis",
          "Trois-Rivières",
          "Terrebonne",
        ],
      },
      {
        name: "British Columbia",
        cities: [
          "Vancouver",
          "Surrey",
          "Burnaby",
          "Richmond",
          "Abbotsford",
          "Coquitlam",
          "Kelowna",
          "Saanich",
          "Delta",
          "Langley",
        ],
      },
      {
        name: "Alberta",
        cities: [
          "Calgary",
          "Edmonton",
          "Red Deer",
          "Lethbridge",
          "St. Albert",
          "Medicine Hat",
          "Grande Prairie",
          "Airdrie",
          "Spruce Grove",
          "Okotoks",
        ],
      },
    ],
  },
  {
    name: "United Kingdom",
    states: [
      {
        name: "England",
        cities: [
          "London",
          "Birmingham",
          "Manchester",
          "Liverpool",
          "Leeds",
          "Sheffield",
          "Bristol",
          "Newcastle",
          "Nottingham",
          "Leicester",
        ],
      },
      {
        name: "Scotland",
        cities: [
          "Glasgow",
          "Edinburgh",
          "Aberdeen",
          "Dundee",
          "Stirling",
          "Perth",
          "Inverness",
          "Paisley",
          "East Kilbride",
          "Hamilton",
        ],
      },
      {
        name: "Wales",
        cities: [
          "Cardiff",
          "Swansea",
          "Newport",
          "Wrexham",
          "Barry",
          "Caerphilly",
          "Bridgend",
          "Neath",
          "Port Talbot",
          "Cwmbran",
        ],
      },
      {
        name: "Northern Ireland",
        cities: [
          "Belfast",
          "Derry",
          "Lisburn",
          "Newtownabbey",
          "Bangor",
          "Craigavon",
          "Castlereagh",
          "Ballymena",
          "Newtownards",
          "Carrickfergus",
        ],
      },
    ],
  },
  {
    name: "Germany",
    states: [
      {
        name: "Bavaria",
        cities: [
          "Munich",
          "Nuremberg",
          "Augsburg",
          "Würzburg",
          "Regensburg",
          "Ingolstadt",
          "Fürth",
          "Erlangen",
          "Bayreuth",
          "Bamberg",
        ],
      },
      {
        name: "North Rhine-Westphalia",
        cities: [
          "Cologne",
          "Düsseldorf",
          "Dortmund",
          "Essen",
          "Duisburg",
          "Bochum",
          "Wuppertal",
          "Bielefeld",
          "Bonn",
          "Münster",
        ],
      },
      {
        name: "Baden-Württemberg",
        cities: [
          "Stuttgart",
          "Mannheim",
          "Karlsruhe",
          "Freiburg",
          "Heidelberg",
          "Ulm",
          "Heilbronn",
          "Pforzheim",
          "Reutlingen",
          "Esslingen",
        ],
      },
      {
        name: "Berlin",
        cities: ["Berlin"],
      },
    ],
  },
  {
    name: "France",
    states: [
      {
        name: "Île-de-France",
        cities: [
          "Paris",
          "Boulogne-Billancourt",
          "Saint-Denis",
          "Argenteuil",
          "Montreuil",
          "Créteil",
          "Nanterre",
          "Colombes",
          "Aulnay-sous-Bois",
          "Rueil-Malmaison",
        ],
      },
      {
        name: "Provence-Alpes-Côte d'Azur",
        cities: [
          "Marseille",
          "Nice",
          "Toulon",
          "Aix-en-Provence",
          "Antibes",
          "Cannes",
          "Avignon",
          "Fréjus",
          "Arles",
          "Hyères",
        ],
      },
      {
        name: "Auvergne-Rhône-Alpes",
        cities: [
          "Lyon",
          "Saint-Étienne",
          "Grenoble",
          "Villeurbanne",
          "Clermont-Ferrand",
          "Valence",
          "Chambéry",
          "Annecy",
          "Bourg-en-Bresse",
          "Roanne",
        ],
      },
      {
        name: "Occitanie",
        cities: [
          "Toulouse",
          "Montpellier",
          "Nîmes",
          "Perpignan",
          "Béziers",
          "Narbonne",
          "Carcassonne",
          "Albi",
          "Tarbes",
          "Bayonne",
        ],
      },
    ],
  },
  {
    name: "Japan",
    states: [
      {
        name: "Tokyo",
        cities: [
          "Tokyo",
          "Hachioji",
          "Tachikawa",
          "Musashino",
          "Mitaka",
          "Ome",
          "Fuchu",
          "Akishima",
          "Chofu",
          "Machida",
        ],
      },
      {
        name: "Osaka",
        cities: [
          "Osaka",
          "Sakai",
          "Higashiosaka",
          "Hirakata",
          "Toyonaka",
          "Suita",
          "Takatsuki",
          "Yao",
          "Ibaraki",
          "Neyagawa",
        ],
      },
      {
        name: "Kanagawa",
        cities: [
          "Yokohama",
          "Kawasaki",
          "Sagamihara",
          "Fujisawa",
          "Chigasaki",
          "Hiratsuka",
          "Odawara",
          "Yamato",
          "Zushi",
          "Kamakura",
        ],
      },
      {
        name: "Aichi",
        cities: [
          "Nagoya",
          "Toyota",
          "Okazaki",
          "Ichinomiya",
          "Seto",
          "Kasugai",
          "Inuyama",
          "Konan",
          "Komaki",
          "Inazawa",
        ],
      },
    ],
  },
  {
    name: "Australia",
    states: [
      {
        name: "New South Wales",
        cities: [
          "Sydney",
          "Newcastle",
          "Wollongong",
          "Maitland",
          "Wagga Wagga",
          "Albury",
          "Port Macquarie",
          "Tamworth",
          "Orange",
          "Dubbo",
        ],
      },
      {
        name: "Victoria",
        cities: [
          "Melbourne",
          "Geelong",
          "Ballarat",
          "Bendigo",
          "Frankston",
          "Mildura",
          "Shepparton",
          "Warrnambool",
          "Pakenham",
          "Sunbury",
        ],
      },
      {
        name: "Queensland",
        cities: [
          "Brisbane",
          "Gold Coast",
          "Townsville",
          "Cairns",
          "Toowoomba",
          "Rockhampton",
          "Mackay",
          "Bundaberg",
          "Hervey Bay",
          "Gladstone",
        ],
      },
      {
        name: "Western Australia",
        cities: [
          "Perth",
          "Fremantle",
          "Rockingham",
          "Mandurah",
          "Bunbury",
          "Kalgoorlie",
          "Geraldton",
          "Albany",
          "Kwinana",
          "Broome",
        ],
      },
    ],
  },
  {
    name: "India",
    states: [
      {
        name: "Maharashtra",
        cities: [
          "Mumbai",
          "Pune",
          "Nagpur",
          "Thane",
          "Nashik",
          "Aurangabad",
          "Solapur",
          "Amravati",
          "Kolhapur",
          "Sangli",
        ],
      },
      {
        name: "Karnataka",
        cities: [
          "Bangalore",
          "Mysore",
          "Hubli",
          "Mangalore",
          "Belgaum",
          "Gulbarga",
          "Davanagere",
          "Bellary",
          "Bijapur",
          "Shimoga",
        ],
      },
      {
        name: "Tamil Nadu",
        cities: [
          "Chennai",
          "Coimbatore",
          "Madurai",
          "Tiruchirappalli",
          "Salem",
          "Tirunelveli",
          "Erode",
          "Vellore",
          "Thoothukudi",
          "Dindigul",
        ],
      },
      {
        name: "Delhi",
        cities: [
          "New Delhi",
          "Delhi",
          "North Delhi",
          "South Delhi",
          "East Delhi",
          "West Delhi",
          "Central Delhi",
          "North East Delhi",
          "North West Delhi",
          "South East Delhi",
        ],
      },
      {
        name: "Gujarat",
        cities: [
          "Ahmedabad",
          "Surat",
          "Vadodara",
          "Rajkot",
          "Bhavnagar",
          "Jamnagar",
          "Junagadh",
          "Gandhinagar",
          "Anand",
          "Navsari",
        ],
      },
    ],
  },
  {
    name: "Brazil",
    states: [
      {
        name: "São Paulo",
        cities: [
          "São Paulo",
          "Guarulhos",
          "Campinas",
          "São Bernardo do Campo",
          "Santo André",
          "Osasco",
          "Ribeirão Preto",
          "Sorocaba",
          "Santos",
          "Mauá",
        ],
      },
      {
        name: "Rio de Janeiro",
        cities: [
          "Rio de Janeiro",
          "São Gonçalo",
          "Duque de Caxias",
          "Nova Iguaçu",
          "Niterói",
          "Belford Roxo",
          "São João de Meriti",
          "Campos dos Goytacazes",
          "Petrópolis",
          "Volta Redonda",
        ],
      },
      {
        name: "Minas Gerais",
        cities: [
          "Belo Horizonte",
          "Uberlândia",
          "Contagem",
          "Juiz de Fora",
          "Betim",
          "Montes Claros",
          "Ribeirão das Neves",
          "Uberaba",
          "Governador Valadares",
          "Ipatinga",
        ],
      },
      {
        name: "Bahia",
        cities: [
          "Salvador",
          "Feira de Santana",
          "Vitória da Conquista",
          "Camaçari",
          "Juazeiro",
          "Itabuna",
          "Lauro de Freitas",
          "Ilhéus",
          "Jequié",
          "Teixeira de Freitas",
        ],
      },
    ],
  },
  {
    name: "China",
    states: [
      {
        name: "Beijing",
        cities: [
          "Beijing",
          "Chaoyang",
          "Haidian",
          "Fengtai",
          "Shijingshan",
          "Mentougou",
          "Fangshan",
          "Tongzhou",
          "Shunyi",
          "Changping",
        ],
      },
      {
        name: "Shanghai",
        cities: [
          "Shanghai",
          "Pudong",
          "Huangpu",
          "Xuhui",
          "Changning",
          "Jing'an",
          "Putuo",
          "Hongkou",
          "Yangpu",
          "Minhang",
        ],
      },
      {
        name: "Guangdong",
        cities: [
          "Guangzhou",
          "Shenzhen",
          "Dongguan",
          "Foshan",
          "Zhongshan",
          "Zhuhai",
          "Jiangmen",
          "Huizhou",
          "Zhaoqing",
          "Shantou",
        ],
      },
      {
        name: "Zhejiang",
        cities: [
          "Hangzhou",
          "Ningbo",
          "Wenzhou",
          "Jiaxing",
          "Huzhou",
          "Shaoxing",
          "Jinhua",
          "Quzhou",
          "Zhoushan",
          "Taizhou",
        ],
      },
    ],
  },
  {
    name: "Russia",
    states: [
      {
        name: "Moscow Oblast",
        cities: [
          "Moscow",
          "Balashikha",
          "Podolsk",
          "Khimki",
          "Mytishchi",
          "Korolev",
          "Lyubertsy",
          "Elektrostal",
          "Kolomna",
          "Krasnogorsk",
          "Sergiev Posad",
          "Orekhovo-Zuyevo",
          "Noginsk",
          "Zhukovsky",
          "Ramenskoye",
          "Pushkino",
          "Shchyolkovo",
          "Dolgoprudny",
        ],
      },
      {
        name: "Saint Petersburg",
        cities: [
          "Saint Petersburg",
          "Kronstadt",
          "Kolpino",
          "Pushkin",
          "Petergof",
          "Lomonosov",
          "Sestroretsk",
          "Zelenogorsk",
          "Pavlovsk",
        ],
      },
      {
        name: "Sverdlovsk Oblast",
        cities: [
          "Yekaterinburg",
          "Nizhny Tagil",
          "Kamensk-Uralsky",
          "Pervouralsk",
          "Serov",
          "Novouralsk",
          "Verkhnyaya Pyshma",
          "Asbest",
          "Revda",
          "Degtyarsk",
          "Aramil",
          "Zarechny",
          "Verkhoturye",
          "Ivdel",
          "Krasnoturinsk",
          "Karpinsk",
        ],
      },
    ],
  },
  {
    name: "Mexico",
    states: [
      {
        name: "Mexico City",
        cities: [
          "Mexico City",
          "Iztapalapa",
          "Ecatepec",
          "Guadalajara",
          "Puebla",
          "Tijuana",
          "León",
          "Juárez",
          "Torreón",
          "Querétaro",
          "San Luis Potosí",
          "Mérida",
          "Mexicali",
          "Aguascalientes",
          "Cuernavaca",
          "Saltillo",
          "Hermosillo",
          "Culiacán",
        ],
      },
      {
        name: "Jalisco",
        cities: [
          "Guadalajara",
          "Zapopan",
          "Tlaquepaque",
          "Tonalá",
          "Puerto Vallarta",
          "Lagos de Moreno",
          "El Salto",
          "Tlajomulco de Zúñiga",
          "Tepatitlán",
          "Ocotlán",
          "Ciudad Guzmán",
          "Arandas",
          "La Barca",
          "Itabuna",
          "Juazeiro",
          "Vitória da Conquista",
          "Camaçari",
          "Ilhéus",
          "Jequié",
          "Teixeira de Freitas",
        ],
      },
      {
        name: "Nuevo León",
        cities: [
          "Monterrey",
          "Guadalupe",
          "San Nicolás de los Garza",
          "Apodaca",
          "General Escobedo",
          "Santa Catarina",
          "San Pedro Garza García",
          "Cadereyta Jiménez",
          "García",
          "Carmen",
          "Juárez",
          "Linares",
          "Montemorelos",
          "Sabinas Hidalgo",
          "Cerralvo",
        ],
      },
    ],
  },
  {
    name: "South Korea",
    states: [
      {
        name: "Seoul",
        cities: [
          "Seoul",
          "Gangnam",
          "Gangdong",
          "Gangbuk",
          "Gangseo",
          "Gwanak",
          "Gwangjin",
          "Guro",
          "Geumcheon",
          "Nowon",
          "Dobong",
          "Dongdaemun",
          "Dongjak",
          "Mapo",
          "Seodaemun",
          "Seocho",
          "Seongdong",
          "Seongbuk",
          "Songpa",
          "Yangcheon",
          "Yeongdeungpo",
          "Yongsan",
          "Eunpyeong",
          "Jongno",
          "Jung",
        ],
      },
      {
        name: "Busan",
        cities: [
          "Busan",
          "Haeundae",
          "Saha",
          "Buk",
          "Sasang",
          "Gangseo",
          "Yeonje",
          "Suyeong",
          "Nam",
          "Dong",
          "Busanjin",
          "Dongnae",
          "Jin",
          "Yeongdo",
          "Seo",
          "Jung",
        ],
      },
      {
        name: "Gyeonggi",
        cities: [
          "Suwon",
          "Seongnam",
          "Goyang",
          "Yongin",
          "Bucheon",
          "Ansan",
          "Anyang",
          "Namyangju",
          "Hwaseong",
          "Pyeongtaek",
          "Uijeongbu",
          "Siheung",
          "Gimpo",
          "Gwangju",
          "Gwangmyeong",
          "Gunpo",
          "Osan",
          "Icheon",
          "Yangju",
          "Hanam",
          "Yeoju",
          "Paju",
          "Dongducheon",
        ],
      },
    ],
  },
]
